services:
  db_geracao:
    image: postgres:16
    #    build: .
    container_name: "geracao_db"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=geracao
#    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - geracao-net

networks:
  geracao-net:
    driver: bridge

volumes:
  db-data:
    name: volume
